### ISSUE TITLE
Problem With Dev Packages

### ISSUE THREAD

**Issue by sho3bshaikh** [moohammed-gaber/before_publish_flutter_cli#1]
After Running  before_publish command it remove already install dev packages for pubspec.yaml.

**Comment by moohammed-gaber** [comment]
I think it fixed in the latest version.

**Comment by moohammed-gaber** [comment]
I recently fixed it in 1.0.2 version, thanks for mention the issue.

**Comment by sho3bshaikh** [comment]
thanks brother.
